### ISSUE TITLE
special keys remains in unknow state

### ISSUE THREAD

**Issue by wasey-rao** [mhamidjamil/ESP32-S3_work#6]
when i press ctrl or other special key like win, alt or shift key they are pressed on backend as expected but i don't know either they are pressed or not so add any color like property on button

**Comment by mhamidjamil** [comment]
this part is added in dev branch please verify it. when you press any special key like `ctrl, win, alt, shift or caps lock` there color will change and they remains pressed until you press them again.

**Comment by wasey-rao** [comment]
@mhamidjamil yes thanks i have check this part is also merged in main code i don't have latest pull, this part is working fine so closing this issue
